### ISSUE TITLE
MacOS 本地部署方法

### ISSUE THREAD

**Issue by larens** [6drf21e/ChatTTS_colab#14]
Google colab的一键部署很方便点赞！

帮助说明中没有介绍mac的本地部署路径，这里给需要的童鞋分享下；
1. 下载 ChatTTS_colab-main 项目文件；
2. 终端进入 ChatTTS_colab-main 目录后需要先安装前置 pip install cn2an
3. 复制原 ChatTTS的项目文件夹到 ChatTTS_colab-main 根目录下；
4. 运行 python webui_mix.py   就自动启动本地界面了；

**Comment by puck1006** [comment]
依赖需要装吗？
