### ISSUE TITLE
大佬，我给你换成夸克网盘了，对不住，我想这个世界上估计只有你还在用百度网盘吧……

### ISSUE THREAD

**Issue by hallejuyahaha** [6drf21e/ChatTTS_colab#18]
我用夸克网盘分享了「Chat-TTS」，点击链接即可保存。打开「夸克APP」，无需下载在线播放视频，畅享原画5倍速，支持电视投屏。
链接：https://pan.quark.cn/s/28ca1e154ede

**Comment by 6drf21e** [comment]
🥲 已加quark
