### ISSUE TITLE
找到了GPU但是还是使用CPU。请问是不是使用姿势不对？

### ISSUE THREAD

**Issue by kkxg** [6drf21e/ChatTTS_colab#2]
![image](https://github.com/6drf21e/ChatTTS_colab/assets/20535377/3b275416-6d13-48b4-820b-20e009feb648)
如图

**Comment by 6drf21e** [comment]
正好 4G 显存的卡不调用GPU的问题 需要修改 ChatTTS/core.py   74 行
![}PILNTOQ~X``$3 (CPHKZ~5](https://github.com/6drf21e/ChatTTS_colab/assets/29720712/6e484c0e-6dda-40a4-a902-c00e597801c3)

 4096 修改成 4095 或者稍低就行了
