### ISSUE TITLE
关于种子管理的音色试听功能

### ISSUE THREAD

**Issue by 3872982** [6drf21e/ChatTTS_colab#21]
一点小建议：
种子管理窗口，能在后面加上种子音色试听功能吗？这样能在种子比较多的时候可以更方便的找到自己想要的种子音色，可以直接在保存种子的时候把对应的音频保存下来

**Comment by bingsunny0730** [comment]
已经有chattts音色库了，https://github.com/kangyiwen/TTSlist/

**Comment by 3872982** [comment]
百度云盘里面下载的版本，修复包也覆盖了，但是配长文本的时候，文本切断处配音处，音色还是有很明显的区别呢，我尝试着多次配短文本，音色却并没有太大的变化

**Comment by 6drf21e** [comment]
> 百度云盘里面下载的版本，修复包也覆盖了，但是配长文本的时候，文本切断处配音处，音色还是有很明显的区别呢，我尝试着多次配短文本，音色却并没有太大的变化

有些种子音色稳定性不太好 下次升级会默认带上一些稳定的音色特征向量
