### ISSUE TITLE
音色种子模型错位，与官方不对应，请求修复

### ISSUE THREAD

**Issue by bingsunny0730** [6drf21e/ChatTTS_colab#28]
本来找到了音色库 http://ttslist.aiqbh.com/ ，但使用指定种子生成的长音频音色与chattts官网的均有偏差，尤其本该是女声种子却会生成男声音色，如42、1400、1800、3333、10400等等。0.0.4新版依旧存在这个问题，估计产生了错位，也就不知道此处真正音色对应的种子数值。请求修复~~

**Comment by 6drf21e** [comment]
不同机器使用相同种子生成的音频音色可能不同，同一机器使用相种子多次生成的音频音色也可能变化。

本机运行的话自己抽卡去固定就可以。

**Comment by bingsunny0730** [comment]
后来测试比较得知，只支持使用CPU的机子和调用GPU的机子使用同一软件同一种子值生成的长文本音色基本一致，只是生成时间不同而已；而chattts-ui也在这两台做了测试，使用同一钟子号生成的音色也相同，且与官网的音色库一一对应。那说明每一种子都有固定且唯一的音色。所以此处的模型库发生错乱了吧？!
另外，音色抽卡部分好像也有个问题，三段话对应生成的一个种子数值音频在换行处会形成不同音调的音色，将多行合为一行反而正常。不知道是不是错乱导致的。

**Comment by bingsunny0730** [comment]
> 不同机器使用相同种子生成的音频音色可能不同，同一机器使用相种子多次生成的音频音色也可能变化。
> 
> 本机运行的话自己抽卡去固定就可以。

您可能理解错啦，后来测试比较得知，只支持使用CPU的机子和调用GPU的机子使用同一软件同一种子值生成的长文本音色基本一致，只是生成时间不同而已；而chattts-ui也在这两台做了测试，使用同一钟子号生成的音色也相同，且与官网的音色库一一对应。那说明每一个种子都有固定且唯一的音色。我可以明白抽卡来指定种子，然而有时找不到好的。故有疑惑，如果是拉取官方库的话，按道理来说应该不会相差太远的吧。所以是不是此处的模型库发生了错乱造成的不一致？

**Comment by 6drf21e** [comment]
固定的方式是通过固定seed使得获取的固定的随机音色 

https://github.com/2noise/ChatTTS/blob/main/ChatTTS/core.py#L177

https://github.com/6drf21e/ChatTTS_colab/blob/main/tts_model.py#L34
可能这一步大家有点区别，模型都一样的

后续会支持导出音色pt文件，换机器也会更稳定。

**Comment by bingsunny0730** [comment]
> 固定的方式是通过固定seed使得获取固定的随机音色
> 
> https://github.com/2noise/ChatTTS/blob/main/ChatTTS/core.py#L177
> 
> https://github.com/6drf21e/ChatTTS_colab/blob/main/tts_model.py#L34 可能这一步大家有点区别，模型都一样的
> 
> 后续会支持导出音色pt文件，换机器也会更稳定。

十分感谢您的解答，还希望后续支持在界面中增加音频（批量）删除的选项，有时忘记删除output文件夹内生成的无用音频就积累占用太多啦

**Comment by 6drf21e** [comment]
https://github.com/6drf21e/ChatTTS_Speaker
2000条说话人音色稳定性评估+男女年龄划分(实验)+在线试听+音色pt文件下载

立即体验：
- 国内：https://modelscope.cn/studios/ttwwwaa/ChatTTS_Speaker
- 抱脸：https://huggingface.co/spaces/taa/ChatTTS_Speaker

新的项目 稳定性评测+音色区分

可以试试能否找到更稳定和喜欢的音色，欢迎反馈。
