### ISSUE TITLE
macos 报错

### ISSUE THREAD

**Issue by zzxxss999** [6drf21e/ChatTTS_colab#35]
git clone git@github.com:6drf21e/ChatTTS_colab.git
Cloning into 'ChatTTS_colab'...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The RSA host key for github.com has changed,
and the key for the corresponding IP address 140.82.114.4
is unknown. This could either mean that
DNS SPOOFING is happening or the IP address for the host
and its host key have changed at the same time.

**Comment by daymade** [comment]
this is not a ChatTTS_colab's problem

**Comment by 6drf21e** [comment]
@zzxxss999 需要给 git 设置下代理 
git config --global http.proxy http://ip:port
git config --global https.proxy http://ip:port
