### ISSUE TITLE
【反馈】中英文混合朗读时，可能有以下2方面问题（附上文本）。

### ISSUE THREAD

**Issue by gemini40** [6drf21e/ChatTTS_colab#42]
可能的问题1：中英文从text复制到文本框内时，点击文本初始化，英文句子之间的单词空格消失了。
可能的问题2：在朗读时，英文句子会读的很奇怪，（如果单独朗读英文句子或段落没有此问题，但是和中文在同一个句子中，朗读会变的很奇怪，吞词、句子读成中文谐音之类）。
可能的问题3（已修复）：就是英文中出现“秒”，将文件正则删除即可。

**文稿如下：**
开心网，有一个对996态度倾向十分明确的修饰，叫做：Notorious so cooded nine nine six work style.
大家好，我是学长，今天我们要讲的是定语从句，Attributive Clause。
谈到定语从句啊，大家都不陌生，这是从初中一直到现在，也是几乎每场大大小小的考试都要出现的。
那定语从句呢，通常可以理解为是英语句子中的一种增强型插件，这个插件呢，可以给句子中的名词，或代词提供更多的信息，使句子变得更具体、更生动。
定语从句通常需要由关系代词引导，比如，who, whom, whose, which, that,.
也或者是关系副词，比如，where when  why来引导。
这个引导代词，一定要紧跟在它们所修饰的名词，或代词的后面。
让我们来举个例子，第一个例子是，The book that I bought yesterday is interesting，我昨天买的书很有趣。
在这个句子中，that I bought yesterday，我昨天购买的，这里就是定语从句，它们修饰了句子中的名词 book。
那另一个例子呢，The woman who lives next door is a doctor. 住在隔壁的女人是一名医生。
在这个句子中，who lives next door，那个住在隔壁的，这个定语就是在修饰句子中的名词 woman。

**烦请作者百忙之中抽时间测试测试，感谢啦！**

**Comment by 6drf21e** [comment]
纯英文/纯中文 没有问题，混合的问题还没有解决。
多谢提供测试文本。估计这周就会更新。

**Comment by 6drf21e** [comment]
> 可能的问题2：在朗读时，英文句子会读的很奇怪，（如果单独朗读英文句子或段落没有此问题，但是和中文在同一个句子中，朗读会变的很奇怪，吞词、句子读成中文谐音之类）。

我也发现了这个问题 试试能不能解决

**Comment by gemini40** [comment]
感谢回复 : )   
首先是克服英文句子导入出现空格消失问题；其次是克服英文读音的问题。①英文句子导入丢失空格，似乎可以添加一种判断机制。②英文句子读出来不清晰这个应该能处理，毕竟纯英文没问题，还是可能是判断上的事情。浅薄之言。

**Comment by gemini40** [comment]
如果搞定，还请您在此帖留言一个，Done  ：）

**Comment by 6drf21e** [comment]
很快会更新

**Comment by 6drf21e** [comment]
> 如果搞定，还请您在此帖留言一个，Done  ：）

英文输出有些问题想请教下 方便加下我qq吗？ **425980**

**Comment by 6drf21e** [comment]
已修复
