### ISSUE TITLE
中文文本情绪和停顿标签不生效问题，bug解决

### ISSUE THREAD

**Issue by suchaunzhi** [6drf21e/ChatTTS_colab#5]
问题在于前端处理文本的时候将[]括号替换掉了，导致ChatTTS不能正确合成。解决：对目前的三种标签做特定判断。

修改utils.py中的remove_chinese_punctuation模块为:

`
def remove_chinese_punctuation(text):
    
    # 使用正则表达式找到所有的[...]括号内的内容
    pattern = r'\[(.*?)\]'
    matches = re.findall(pattern, text)

    # 遍历每个括号内的内容
    for match in matches:
        if match != "uv_break" and match != "laugh" and match != "lbreak":
            text = text.replace("[" + match + "]", match)

    chinese_punctuation_pattern = r"[：；！（），【】『』「」《》－‘“’”:,;!\(\)><]"
    text = re.sub(chinese_punctuation_pattern, ' ', text)
    # 使用正则表达式将多个连续的句号替换为一个句号
    text = re.sub(r'。{2,}', '。', text)
    return text
`

作者如果觉得可行，望采纳

**Comment by suchaunzhi** [comment]
这个代码块真难用 T_T

**Comment by jinny76** [comment]
其实我想自己写， 如果有官方那种， 可以切换是否refine也可以接受

**Comment by suchaunzhi** [comment]
> 其实我想自己写， 如果有官方那种， 可以切换是否refine也可以接受

感觉官方可能没空管这些前端问题。发现了[]括号的问题，但是只是简单做了个注释，还没注释全😢

**Comment by 6drf21e** [comment]
第一个版本做的简单 没有做 refientxt 开关 下版本加上😊
