### ISSUE TITLE
为什么我的没有本地ollama选项？

### ISSUE THREAD

**Issue by kenic123** [6drf21e/ChatTTS_colab#51]
为什么我的没有本地ollama选项？
![1718994196013](https://github.com/6drf21e/ChatTTS_colab/assets/67681738/b8b6994c-e652-408c-8ae1-ca12cb7eddde)

**Comment by kenic123** [comment]
有人和我一样吗？

**Comment by 6drf21e** [comment]
#40 还没合并 准备周末合并
你可去up主那边有打包好的

**Comment by kenic123** [comment]
QQ群满了，B站还没回复，不知道找到UP了

**Comment by kenic123** [comment]
> #40 还没合并 准备周末合并 你可去up主那边有打包好的
替换文件后已经好了，感谢！
