### ISSUE TITLE
mac 启动报错

### ISSUE THREAD

**Issue by ccj** [6drf21e/ChatTTS_colab#67]
(base) ccj@192 ChatTTS_colab % python webui_mix.py
/Users/ccj/Desktop/project/ChatTTS_colab/utils.py:99: SyntaxWarning: invalid escape sequence '\('
  """
/Users/ccj/Desktop/project/ChatTTS_colab/utils.py:113: SyntaxWarning: invalid escape sequence '\('
  """
/Users/ccj/Desktop/project/ChatTTS_colab/utils.py:327: SyntaxWarning: invalid escape sequence '\~'
  "12\~23 -1.5\~2",
Loading ChatTTS model...
Traceback (most recent call last):
  File "/Users/ccj/Desktop/project/ChatTTS_colab/webui_mix.py", line 46, in <module>
    chat = load_chat_tts_model(source=args.source, local_path=args.local_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ccj/Desktop/project/ChatTTS_colab/tts_model.py", line 25, in load_chat_tts_model
    chat.load_models(source=source, force_redownload=force_redownload, custom_path=local_path, compile=False)
TypeError: Chat.load_models() got an unexpected keyword argument 'custom_path'

**Comment by 6drf21e** [comment]
需要更新下 ChatTTS

**Comment by 6drf21e** [comment]
```
git clone -q https://github.com/2noise/ChatTTS
cd ChatTTS
git checkout -q e6412b1
```
---
第五步需要修改为这个

**Comment by ccj** [comment]
可以了非常感谢

**Comment by killy001** [comment]
遇到同样的问题，

是说这个步骤：
```
git clone -q https://github.com/2noise/ChatTTS
cd ChatTTS
git checkout -q e6412b1
cd ..
mv ChatTTS temp
mv temp/ChatTTS ./ChatTTS
rm -rf temp
```


替换成下面这个吗？
```
git clone -q https://github.com/2noise/ChatTTS
cd ChatTTS
git checkout -q e6412b1
```
