### ISSUE TITLE
目前做的最好最全面的UI，可惜控制停顿和笑声的文本输入不生效，如果能再加入添加停顿和笑声的按钮，那就更好了。

### ISSUE THREAD

**Issue by bellnales** [6drf21e/ChatTTS_colab#8]
目前做的最好最全面的UI，可惜控制停顿和笑声的文本输入不生效，如果能再加入添加停顿和笑声的按钮，那就更好了。
比如： 
![示意图](https://github.com/6drf21e/ChatTTS_colab/assets/120457526/5ff56fcf-2c72-4999-a9cf-bcce581271a3)

**Comment by Jimi-from-mars** [comment]
我也发现了，手工添加笑声和停顿的标签不起作用。

**Comment by 1668768637** [comment]
解决了，在utils.py的第90行改为   chinese_punctuation_pattern = r"[：；！（），【】『』「」《》－‘“’”:,;!\(\)><\-]"  就可以了.
看到dos界面的消息中[]没有被过滤掉就好了
![1](https://github.com/6drf21e/ChatTTS_colab/assets/62231647/27b1113c-e021-44eb-83fb-0e9465179b1c)
![2](https://github.com/6drf21e/ChatTTS_colab/assets/62231647/8e37737d-00fb-424f-9adc-0c54115eb0d7)

**Comment by 1668768637** [comment]
> 我也发现了，手工添加笑声和停顿的标签不起作用。

看我的评论
