### ISSUE TITLE
下载好了运行显示这个，请问要怎么弄呀 

### ISSUE THREAD

**Issue by wu435328454** [6drf21e/ChatTTS_colab#82]
![微信截图_20240801054651](https://github.com/user-attachments/assets/94854ccf-2218-480c-bddf-a668a0fe7f38)

**Comment by Jimi-from-mars** [comment]
估计是你代理软件里的路由设置禁止了访问localhost，关掉代理软件试试。

**Comment by 6drf21e** [comment]
需要关闭全局代理
